<?php
$data = array (
  0 => 
  array (
    'cat_id' => '76',
    'cat_name' => '生鲜水果',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  1 => 
  array (
    'cat_id' => '77',
    'cat_name' => '干果零食',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '47',
  ),
  2 => 
  array (
    'cat_id' => '78',
    'cat_name' => '酒水饮料',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  3 => 
  array (
    'cat_id' => '79',
    'cat_name' => '美妆护肤',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => '24',
  ),
  4 => 
  array (
    'cat_id' => '80',
    'cat_name' => '母婴用品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  5 => 
  array (
    'cat_id' => '81',
    'cat_name' => '服装饰品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => '62',
  ),
  6 => 
  array (
    'cat_id' => '82',
    'cat_name' => '日用百货',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '0',
    'goods_num' => '48',
  ),
  7 => 
  array (
    'cat_id' => '83',
    'cat_name' => '家居用品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '80',
    'has_children' => '0',
    'goods_num' => '22',
  ),
);
?>