<?php
$data = array (
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '生鲜水果',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 0,
    'id' => '76',
    'name' => '生鲜水果',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '干果零食',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '47',
    'level' => 0,
    'id' => '77',
    'name' => '干果零食',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '酒水饮料',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 0,
    'id' => '78',
    'name' => '酒水饮料',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '美妆护肤',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => '24',
    'level' => 0,
    'id' => '79',
    'name' => '美妆护肤',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '母婴用品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '80',
    'name' => '母婴用品',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '服装饰品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => '62',
    'level' => 0,
    'id' => '81',
    'name' => '服装饰品',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '日用百货',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '0',
    'goods_num' => '48',
    'level' => 0,
    'id' => '82',
    'name' => '日用百货',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '家居用品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '80',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 0,
    'id' => '83',
    'name' => '家居用品',
  ),
);
?>